// IPC channel names — the single source of truth shared by the main-process
// handlers and the preload bridge. Plain constants, no runtime imports.

export const CHANNELS = {
  ping: 'aerie:ping',
  accountsAdd: 'accounts:add',
  accountsList: 'accounts:list',
  accountsRemove: 'accounts:remove',
  accountsRefresh: 'accounts:refresh',
  accountsRateLimit: 'accounts:rateLimit',
  accountsUpdateToken: 'accounts:updateToken',
  reposList: 'repos:list',
  reposRefresh: 'repos:refresh',
  reposSetFavorite: 'repos:setFavorite',
  repoBranches: 'repo:branches',
  repoCommits: 'repo:commits',
  repoCommit: 'repo:commit',
  repoPulls: 'repo:pulls',
  repoPull: 'repo:pull',
  mappingGet: 'mapping:get',
  mappingPickLocal: 'mapping:pickLocal',
  mappingClearLocal: 'mapping:clearLocal',
  mappingSetUseLocal: 'mapping:setUseLocal',
  gitPrepare: 'git:prepare',
  runnerListAgents: 'runner:listAgents',
  runnerListCandidates: 'runner:listCandidates',
  runnerDiscoverAgents: 'runner:discoverAgents',
  runnerApproveAgent: 'runner:approveAgent',
  runnerGetAgent: 'runner:getAgent',
  runnerSaveAgent: 'runner:saveAgent',
  runnerDeleteAgent: 'runner:deleteAgent',
  runnerCloneAgent: 'runner:cloneAgent',
  runnerSetAgentModel: 'runner:setAgentModel',
  runnerSetAgentReasoning: 'runner:setAgentReasoning',
  runnerStart: 'runner:start',
  runnerStartBatch: 'runner:startBatch',
  presetsList: 'presets:list',
  presetsSave: 'presets:save',
  presetsDelete: 'presets:delete',
  promptsList: 'prompts:list',
  promptsSave: 'prompts:save',
  promptsDelete: 'prompts:delete',
  runnerKill: 'runner:kill',
  runnerListRuns: 'runner:listRuns',
  runnerReadOutput: 'runner:readOutput',
  runnerFindings: 'runner:findings',
  runnerConsensus: 'runner:consensus',
  runnerTranscript: 'runner:transcript',
  runnerSetLocalStatus: 'runner:setLocalStatus',
  runsListAll: 'runs:listAll',
  pipelinesList: 'pipelines:list',
  pipelinesSave: 'pipelines:save',
  pipelinesDelete: 'pipelines:delete',
  pipelinesSetEnabled: 'pipelines:setEnabled',
  pipelinesRunNow: 'pipelines:runNow',
  pipelinesDryRun: 'pipelines:dryRun',
  pipelinesPollerStatus: 'pipelines:pollerStatus',
  githubPost: 'github:post',
  systemInfo: 'system:info',
  systemOpenPath: 'system:openPath',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  // main → renderer push channels
  runnerOutput: 'runner:output',
  runnerStatus: 'runner:status',
  pipelineStatus: 'pipeline:status',
  trayOpenRun: 'tray:openRun'
} as const
