// IPC channel names — the single source of truth shared by the main-process
// handlers and the preload bridge. Plain constants, no runtime imports.

export const CHANNELS = {
  ping: 'aerie:ping',
  accountsAdd: 'accounts:add',
  accountsList: 'accounts:list',
  accountsRemove: 'accounts:remove',
  accountsRefresh: 'accounts:refresh',
  accountsUpdateToken: 'accounts:updateToken',
  reposList: 'repos:list',
  reposRefresh: 'repos:refresh',
  repoBranches: 'repo:branches',
  repoCommits: 'repo:commits',
  repoCommit: 'repo:commit',
  repoPulls: 'repo:pulls',
  repoPull: 'repo:pull',
  mappingGet: 'mapping:get',
  mappingPickLocal: 'mapping:pickLocal',
  mappingClearLocal: 'mapping:clearLocal',
  mappingSetUseLocal: 'mapping:setUseLocal',
  gitPrepare: 'git:prepare',
  runnerListAgents: 'runner:listAgents',
  runnerSetAgentModel: 'runner:setAgentModel',
  runnerSetAgentReasoning: 'runner:setAgentReasoning',
  runnerStart: 'runner:start',
  presetsList: 'presets:list',
  presetsSave: 'presets:save',
  presetsDelete: 'presets:delete',
  promptsList: 'prompts:list',
  promptsSave: 'prompts:save',
  promptsDelete: 'prompts:delete',
  runnerKill: 'runner:kill',
  runnerListRuns: 'runner:listRuns',
  runnerReadOutput: 'runner:readOutput',
  runnerTranscript: 'runner:transcript',
  runsListAll: 'runs:listAll',
  githubPost: 'github:post',
  systemInfo: 'system:info',
  systemOpenPath: 'system:openPath',
  // main → renderer push channels
  runnerOutput: 'runner:output',
  runnerStatus: 'runner:status'
} as const
